#!/bin/bash

#export BITS=32
#export ARCH=i686
export BITS=64
export ARCH=x86_64

export NACL_SDK_ROOT=~/nacl_sdk/pepper_21
export NACL_SDK_BIN=${NACL_SDK_ROOT}/toolchain/linux_x86_glibc/bin
export NACL_SDK_LIB=${NACL_SDK_ROOT}/toolchain/linux_x86_glibc/x86_64-nacl/lib${BITS}
export NACL_TOOLS=${NACL_SDK_ROOT}/tools
export NACL_SEL_LDR=${NACL_TOOLS}/sel_ldr_x86_${BITS}
export NACL_IRT=${NACL_TOOLS}/irt_x86_${BITS}.nexe

export SRC_DIR="$(cd ../gforth-0.7.0 && pwd)"

export TARGET_RUN="${SRC_DIR}/nacl_run "

function conf() {
  ${SRC_DIR}/configure \
      --host=${ARCH}-nacl \
      CC="${NACL_SDK_BIN}/${ARCH}-nacl-gcc"
}
