#!/bin/bash

set -e
set -x

. nacl/nacl_setup.sh

function main() {
  rm -rf out
  mkdir out

  genconfig

  forbits 32
  config
  make -C out/obj32

  forbits 64
  config
  make -C out/obj64

  mkdir -p out/publish
  cp out/obj32/gforth.nexe out/publish/gforth_x86_32.nexe
  cp out/obj64/gforth.nexe out/publish/gforth_x86_64.nexe

  # Create nmf.
  cd out/publish
  python ${NACL_TOOLS}/create_nmf.py \
      -o gforth.nmf \
      -L ${NACL_SDK_LIB_BASE}32 \
      -L ${NACL_SDK_LIB_BASE}64 \
      -t glibc \
      gforth_x86_32.nexe \
      gforth_x86_64.nexe \
      -s .
  cd ${SRC_DIR}

  tar cf out/publish/gforth32.tar -C out/obj32 gforth.fi
  tar cf out/publish/gforth64.tar -C out/obj64 gforth.fi
  cp ${SRC_DIR}/nacl/index.html out/publish
  cp ${SRC_DIR}/nacl/gforth.js out/publish
  cp ${SRC_DIR}/nacl/manifest.json out/publish
  cp ${SRC_DIR}/nacl/icon_*.png out/publish
  zip -r out/publish.zip out/publish
}

main
